In [ ]:
"""4.1 Exercise on Functions:**
Task - 1:
Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.
• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.
• Conversion Options:
1. Length:
– Convert meters (m) to feet (ft).
– Convert feet (ft) to meters (m).
2. Weight:
– Convert kilograms (kg) to pounds (lbs).
– Convert pounds (lbs) to kilograms (kg).
3. Volume:
– Convert liters (L) to gallons (gal).
– Convert gallons (gal) to liters (L)."""

In [1]:
def convert_units(conversion_type, value):
    """
    Converts units based on selected conversion type.

    Parameters:
    conversion_type (int): The option number chosen by the user.
    value (float): The numeric value to convert.

    Returns:
    float: Converted value.
    """

    if conversion_type == 1:
        return value * 3.28084
    elif conversion_type == 2:
        return value / 3.28084

    elif conversion_type == 3:
        return value * 2.20462
    elif conversion_type == 4:
        return value / 2.20462

    elif conversion_type == 5:
        return value * 0.264172
    elif conversion_type == 6:
        return value / 0.264172

    else:
        return None



print("Unit Converter")
print("1. Meters to Feet")
print("2. Feet to Meters")
print("3. Kilograms to Pounds")
print("4. Pounds to Kilograms")
print("5. Liters to Gallons")
print("6. Gallons to Liters")

try:
    choice = int(input("Choose conversion type (1-6): "))
    value = float(input("Enter the value to convert: "))

    result = convert_units(choice, value)

    if result is None:
        print("Invalid conversion type selected.")
    else:
        print("Converted value:", result)

except ValueError:
    print("Invalid input! Please enter numeric values only.")

Unit Converter
1. Meters to Feet
2. Feet to Meters
3. Kilograms to Pounds
4. Pounds to Kilograms
5. Liters to Gallons
6. Gallons to Liters
Choose conversion type (1-6): 3
Enter the value to convert: 2
Converted value: 4.40924


In [ ]:

""" Create a Python program that performs various mathematical operations on a list of numbers.
• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).
3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.
• Requirements:

1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).

2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value. """

In [2]:
def calculate_sum(numbers):
    """
    Returns the sum of numbers in the list.

    Parameters:
    numbers (list): List of numeric values.

    Returns:
    float: Sum of the numbers.
    """
    return sum(numbers)


def calculate_average(numbers):
    """
    Returns the average of numbers in the list.

    Parameters:
    numbers (list): List of numeric values.

    Returns:
    float: Average of the numbers.
    """
    return sum(numbers) / len(numbers)


def find_max(numbers):
    """
    Returns the maximum number in the list.

    Parameters:
    numbers (list): List of numeric values.

    Returns:
    float: Maximum value.
    """
    return max(numbers)


def find_min(numbers):
    """
    Returns the minimum number in the list.

    Parameters:
    numbers (list): List of numeric values.

    Returns:
    float: Minimum value.
    """
    return min(numbers)


print("Select operation:")
print("1. Sum")
print("2. Average")
print("3. Maximum")
print("4. Minimum")

try:
    choice = input("Enter choice (1-4): ")

    user_input = input("Enter numbers separated by spaces: ")
    numbers = list(map(float, user_input.split()))

    if len(numbers) == 0:
        raise ValueError("List cannot be empty.")

    if choice == "1":
        print("Sum:", calculate_sum(numbers))
    elif choice == "2":
        print("Average:", calculate_average(numbers))
    elif choice == "3":
        print("Maximum:", find_max(numbers))
    elif choice == "4":
        print("Minimum:", find_min(numbers))
    else:
        print("Invalid choice.")

except ValueError:
    print("Invalid input! Please enter numeric values only and do not leave empty.")

Select operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter choice (1-4): 4
Enter numbers separated by spaces: 4
Minimum: 4.0


In [ ]:
"""4.2 Exercise on List Manipulation:**
1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.
• Requirements:
– Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].
2. Slice a Sublist:
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.
• Requirements:
– Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).
– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].

3. Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing.
• Requirements:
– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].
4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.
• Requirements:
– Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].
5. Get the First n Elements:
Write a Python function that extracts the first n elements from a list.
• Requirements:
– Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.
– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].
6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.
• Requirements:
– Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.
– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].
7. Extract Elements in Reverse Order:
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.
• Requirements:
– Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1]. """

In [3]:

def extract_every_other(lst):
    """Returns every other element starting from the first element."""
    return lst[::2]

def get_sublist(lst, start, end):
    """Returns sublist from start to end index (inclusive)."""
    return lst[start:end+1]

def reverse_list(lst):
    """Returns the reversed list."""
    return lst[::-1]

def remove_first_last(lst):
    """Removes first and last elements."""
    return lst[1:-1]

def get_first_n(lst, n):
    """Returns first n elements of the list."""
    return lst[:n]

def get_last_n(lst, n):
    """Returns last n elements of the list."""
    return lst[-n:]

def reverse_skip(lst):
    """Returns every second element starting from second-to-last, moving backward."""
    return lst[-2::-2]


sample_list = [1, 2, 3, 4, 5, 6]

print("Original List:", sample_list)

print("1. Every other element:", extract_every_other(sample_list))
print("2. Sublist (index 2 to 4):", get_sublist(sample_list, 2, 4))
print("3. Reversed list:", reverse_list(sample_list))
print("4. Remove first and last:", remove_first_last(sample_list))
print("5. First 3 elements:", get_first_n(sample_list, 3))
print("6. Last 2 elements:", get_last_n(sample_list, 2))
print("7. Reverse skip:", reverse_skip(sample_list))

Original List: [1, 2, 3, 4, 5, 6]
1. Every other element: [1, 3, 5]
2. Sublist (index 2 to 4): [3, 4, 5]
3. Reversed list: [6, 5, 4, 3, 2, 1]
4. Remove first and last: [2, 3, 4, 5]
5. First 3 elements: [1, 2, 3]
6. Last 2 elements: [5, 6]
7. Reverse skip: [5, 3, 1]


In [ ]:
"""4.3 Exercise on Nested List:**
1. Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.
• Requirements:
– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.
– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].
2. Accessing Nested List Elements:
Write a Python function that extracts a specific element from a nested list given its indices.
• Requirements:
– Define a function access nested element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.
– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.
3. Sum of All Elements in a Nested List:
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).
• Requirements:
– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
the elements.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.
4. Remove Specific Element from a Nested List:
Write a Python function that removes all occurrences of a specific element from a nested list.
• Requirements:
– Define a function remove element(lst, elem) that removes elem from lst and returns the
modified list.
– Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
be [[1], [3], [4, 5]].

5. Find the Maximum Element in a Nested List:
Write a Python function that finds the maximum element in a nested list (regardless of depth).
• Requirements:
– Define a function find max(lst) that takes a nested list lst and returns the maximum
element.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.
6. Count Occurrences of an Element in a Nested List:
Write a Python function that counts how many times a specific element appears in a nested list.
• Requirements:
– Define a function count occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.
– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
be 3.

7. Flatten a List of Lists of Lists:
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.
• Requirements:
– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
flattened list.
– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].

8. Nested List Average:
Write a Python function that calculates the average of all elements in a nested list.
• Requirements:
– Define a function average nested(lst) that takes a nested list lst and returns the average
of all the elements.
– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5. """

In [4]:

def flatten(lst):
    """Flattens a 2D nested list into a single list."""
    result = []
    for sub in lst:
        for item in sub:
            result.append(item)
    return result


def access_nested_element(lst, indices):
    """Returns element from nested list using list of indices."""
    element = lst
    for index in indices:
        element = element[index]
    return element

def sum_nested(lst):
    """Returns sum of all elements in nested list."""
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

def remove_element(lst, elem):
    """Removes all occurrences of elem from nested list."""
    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)
    return result

def find_max(lst):
    """Returns maximum element in nested list."""
    max_value = None
    for item in lst:
        if isinstance(item, list):
            value = find_max(item)
        else:
            value = item

        if max_value is None or value > max_value:
            max_value = value
    return max_value

def count_occurrences(lst, elem):
    """Counts occurrences of elem in nested list."""
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

def deep_flatten(lst):
    """Flattens a deeply nested list into a single list."""
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

def average_nested(lst):
    """Returns average of all elements in nested list."""
    flat = deep_flatten(lst)
    return sum(flat) / len(flat)



print("1. Flatten:", flatten([[1,2],[3,4],[5]]))

print("2. Access Element:",
      access_nested_element([[1,2,3],[4,5,6],[7,8,9]], [1,2]))

print("3. Sum Nested:",
      sum_nested([[1,2],[3,[4,5]],6]))

print("4. Remove Element:",
      remove_element([[1,2],[3,2],[4,5]], 2))

print("5. Find Max:",
      find_max([[1,2],[3,[4,5]],6]))

print("6. Count Occurrences:",
      count_occurrences([[1,2],[2,3],[2,4]], 2))

print("7. Deep Flatten:",
      deep_flatten([[[1,2],[3,4]],[[5,6],[7,8]]]))

print("8. Average Nested:",
      average_nested([[1,2],[3,4],[5,6]]))

1. Flatten: [1, 2, 3, 4, 5]
2. Access Element: 6
3. Sum Nested: 21
4. Remove Element: [[1], [3], [4, 5]]
5. Find Max: 6
6. Count Occurrences: 3
7. Deep Flatten: [1, 2, 3, 4, 5, 6, 7, 8]
8. Average Nested: 3.5


In [ ]:
"""10.1 Basic Vector and Matrix Operation with Numpy.**
Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()} """

In [5]:
import numpy as np

empty_array = np.empty((2, 2))
print("1. Empty 2x2 Array:")
print(empty_array)


ones_array = np.ones((4, 2))
print("\n2. Ones 4x2 Array:")
print(ones_array)


full_array = np.full((3, 3), 7)
print("\n3. Full Array (3x3 filled with 7):")
print(full_array)


zeros_like_array = np.zeros_like(ones_array)
print("\n4. Zeros Like Array (same shape as ones_array):")
print(zeros_like_array)

ones_like_array = np.ones_like(full_array)
print("\n5. Ones Like Array (same shape as full_array):")
print(ones_like_array)


new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\n6. List Converted to NumPy Array:")
print(numpy_array)

1. Empty 2x2 Array:
[[2.33514036e-316 0.00000000e+000]
 [6.60175101e-310 6.60176767e-310]]

2. Ones 4x2 Array:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Full Array (3x3 filled with 7):
[[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros Like Array (same shape as ones_array):
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

5. Ones Like Array (same shape as full_array):
[[1 1 1]
 [1 1 1]
 [1 1 1]]

6. List Converted to NumPy Array:
[1 2 3 4]


In [ ]:
"""Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:**
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern. """

In [6]:
import numpy as np

arr1 = np.arange(10, 50)
print("1) 10 to 49:\n", arr1)

arr2 = np.arange(0, 9).reshape(3, 3)
print("\n2) 3x3 matrix (0 to 8):\n", arr2)

arr3 = np.eye(3)
print("\n3) Identity 3x3:\n", arr3)

arr4 = np.random.random(30)
print("\n4) Random array (size 30):\n", arr4)
print("Mean:", arr4.mean())

arr5 = np.random.random((10, 10))
print("\n5) 10x10 random array:\n", arr5)
print("Min:", arr5.min())
print("Max:", arr5.max())

arr6 = np.zeros(10)
arr6[4] = 1
print("\n6) Zero array with 5th element = 1:\n", arr6)

arr7 = np.array([1, 2, 0, 0, 4, 0])
reversed_arr7 = arr7[::-1]
print("\n7) Reversed array:\n", reversed_arr7)

arr8 = np.ones((5, 5))
arr8[1:-1, 1:-1] = 0
print("\n8) 2D border 1, inside 0:\n", arr8)

checker = np.zeros((8, 8), dtype=int)
checker[::2, 1::2] = 1
checker[1::2, ::2] = 1
print("\n9) 8x8 Checkerboard:\n", checker)

1) 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2) 3x3 matrix (0 to 8):
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3) Identity 3x3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4) Random array (size 30):
 [0.94781457 0.92682488 0.93236547 0.62760696 0.4478366  0.25976785
 0.20366734 0.58970307 0.42568693 0.48251958 0.60204018 0.67429021
 0.83271362 0.401391   0.04867889 0.4943948  0.93412938 0.91022799
 0.32189834 0.29850448 0.69602063 0.09213909 0.90208376 0.4931764
 0.84056992 0.0133768  0.37151044 0.70168392 0.6339862  0.30551534]
Mean: 0.5470708217505243

5) 10x10 random array:
 [[0.15152347 0.88887076 0.09301368 0.85750326 0.19880919 0.14837611
  0.14108404 0.93822954 0.16149103 0.37827412]
 [0.59421826 0.80810709 0.60581934 0.61397683 0.77127304 0.92168187
  0.7200921  0.81520659 0.31233973 0.86368803]
 [0.64449777 0.35018697 0.18259048 0.91528312 0.83383951 0.13638143
  0.22815083 0.71943172 0.85124701 0.5207

In [ ]:
"""Problem - 3: Array Operations:**
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error? """

In [7]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

print("x:\n", x)
print("y:\n", y)
print("v:", v)
print("w:", w)

print("\n1) x + y:\n", x + y)

print("\n2) x - y:\n", x - y)

print("\n3) x * 3:\n", x * 3)

print("\n4) Square of x:\n", x**2)

print("\n5a) Dot product v · w:", np.dot(v, w))
print("5b) Dot product x · v:\n", np.dot(x, v))
print("5c) Dot product x · y:\n", np.dot(x, y))

print("\n6a) Concatenate x and y (rows):\n", np.vstack((x, y)))

print("\n6b) Concatenate v and w (column):\n", np.column_stack((v, w)))

try:
    print("\n7) Concatenate x and v:\n", np.concatenate((x, v)))
except ValueError as e:
    print("\n7) Error while concatenating x and v:")
    print(e)

# Explanation:
# Error occurs because x is 2D and v is 1D.
# Dimensions must match for concatenation.

x:
 [[1 2]
 [3 5]]
y:
 [[5 6]
 [7 8]]
v: [ 9 10]
w: [11 12]

1) x + y:
 [[ 6  8]
 [10 13]]

2) x - y:
 [[-4 -4]
 [-4 -3]]

3) x * 3:
 [[ 3  6]
 [ 9 15]]

4) Square of x:
 [[ 1  4]
 [ 9 25]]

5a) Dot product v · w: 219
5b) Dot product x · v:
 [29 77]
5c) Dot product x · y:
 [[19 22]
 [50 58]]

6a) Concatenate x and y (rows):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

6b) Concatenate v and w (column):
 [[ 9 11]
 [10 12]]

7) Error while concatenating x and v:
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [ ]:
"""Problem - 4: Matrix Operations:**

For the following arrays:

A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy} """

In [8]:
import numpy as np

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# 1. Prove A.A^-1 = I
A_inv = np.linalg.inv(A)
print("A * A_inv:\n", np.dot(A, A_inv))

# 2. Prove AB ≠ BA
print("AB:\n", np.dot(A,B))
print("BA:\n", np.dot(B,A))

# 3. Prove (AB)^T = B^T A^T
left = np.dot(A,B).T
right = np.dot(B.T, A.T)
print("(AB)^T:\n", left)
print("B^T A^T:\n", right)

A * A_inv:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
(AB)^T:
 [[23 51]
 [13 29]]
B^T A^T:
 [[23 51]
 [13 29]]


In [12]:
A = np.array([[2,-3,1],
              [1,-1,2],
              [3,1,-1]])

B = np.array([-1,-3,9])

# Using inverse
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)

print("Solution using inverse:", X)

# Direct solve method (better method)
X2 = np.linalg.solve(A,B)
print("Solution using solve():", X2)

Solution using inverse: [ 2.  1. -2.]
Solution using solve(): [ 2.  1. -2.]


In [10]:
import time

In [ ]:
"""10.2 Experiment: How Fast is Numpy?**

In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:"""

"""1. Element-wise Addition:**

• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation."""

In [13]:
import time
import numpy as np

# Size
n = 1_000_000

# Using Python Lists


list1 = list(range(n))
list2 = list(range(n))

start = time.time()

result_list = [list1[i] + list2[i] for i in range(n)]

end = time.time()

print("Python List Time:", end - start, "seconds")


# Using NumPy Arrays

arr1 = np.arange(n)
arr2 = np.arange(n)

start = time.time()

result_array = arr1 + arr2

end = time.time()

print("NumPy Array Time:", end - start, "seconds")

Python List Time: 0.12821269035339355 seconds
NumPy Array Time: 0.007374286651611328 seconds


In [ ]:
"""2. Element-wise Multiplication**

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation."""

In [14]:
import time
import numpy as np

# Size
n = 1_000_000

# Using Python Lists

list1 = list(range(n))
list2 = list(range(n))

start = time.time()

result_list = [list1[i] * list2[i] for i in range(n)]

end = time.time()

print("Python List Multiplication Time:", end - start, "seconds")


# Using NumPy Arrays

arr1 = np.arange(n)
arr2 = np.arange(n)

start = time.time()

result_array = arr1 * arr2

end = time.time()

print("NumPy Array Multiplication Time:", end - start, "seconds")

Python List Multiplication Time: 0.1906592845916748 seconds
NumPy Array Multiplication Time: 0.004761934280395508 seconds


In [ ]:
"""3. Dot Product**

• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation. """

In [15]:
import time
import numpy as np

# Size
n = 1_000_000

# Using Python Lists

list1 = list(range(n))
list2 = list(range(n))

start = time.time()

dot_product_list = 0
for i in range(n):
    dot_product_list += list1[i] * list2[i]

end = time.time()

print("Python List Dot Product Time:", end - start, "seconds")

# Using NumPy Arrays

arr1 = np.arange(n)
arr2 = np.arange(n)

start = time.time()

dot_product_array = np.dot(arr1, arr2)

end = time.time()

print("NumPy Dot Product Time:", end - start, "seconds")

Python List Dot Product Time: 0.21714043617248535 seconds
NumPy Dot Product Time: 0.001918792724609375 seconds


In [ ]:
"""4. Matrix Multiplication**

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation. """

In [19]:
import time
import numpy as np

n = 1000

# Using Python Lists

A_list = [[i for i in range(n)] for _ in range(n)]
B_list = [[i for i in range(n)] for _ in range(n)]

start = time.time()

result_list = [[0]*n for _ in range(n)]

for i in range(n):
    for j in range(n):
        for k in range(n):
            result_list[i][j] += A_list[i][k] * B_list[k][j]

end = time.time()

print("Python List Matrix Multiplication Time:", end - start, "seconds")


# Using NumPy Arrays

A_np = np.arange(n*n).reshape(n, n)
B_np = np.arange(n*n).reshape(n, n)

start = time.time()

result_np = np.dot(A_np, B_np)

end = time.time()

print("NumPy Matrix Multiplication Time:", end - start, "seconds")

Python List Matrix Multiplication Time: 375.50163555145264 seconds
NumPy Matrix Multiplication Time: 1.8702428340911865 seconds
